import {RULES as R} from './rules.mjs';
export const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
export const defaults={age:60,retirementAge:65,relationshipStatus:'single',superBalance:600000,partnerSuper:400000,partnerAge:60,otherAssets:30000,nonFinancialAssets:10000,otherIncome:0,homeowner:true,desiredIncome:55000,knownExpenses:0,pensionExpectation:'estimate',lifetimePayout:5.5};
export const defaultPreferences={earlyLifestyle:1,emergencySecurity:1,lifetimeCertainty:1,liquidity:1,legacy:1,laterSpending:1};
export function initialControls(p){return {enjoy:[75,50,25][p.earlyLifestyle]+[10,0,-10][p.laterSpending],certainty:clamp([80,50,10][p.lifetimeCertainty]+[-25,0,15][p.liquidity],0,100),buffer:[85,50,15][p.emergencySecurity],legacy:[85,50,10][p.legacy]};}
export function grossRetirementCapital(p){return Math.max(0,(p.superBalance+(p.relationshipStatus==='couple'?p.partnerSuper:0))*Math.pow(1.02,Math.max(0,p.retirementAge-p.age))+p.otherAssets);}
export function retirementCapital(p){return Math.max(0,grossRetirementCapital(p)-p.knownExpenses);}
export function allocation(c,p){const L=5+15*c.buffer/100,E=40*c.certainty/100,rest=100-L-E;const f=clamp(.48-.23*c.enjoy/100+.25*c.legacy/100,.2,.8);return {L,I:rest*(1-f),F:rest*f,E};}
export function deriveInitialLifeAllocation(profile,p){return allocation(initialControls(p),profile);}
export function deriveInvestmentApproach(p,prefs,a){return a.F>40&&95-p.retirementAge>25?'Growth':a.L>=19&&a.E>=20?'Conservative':'Balanced';}
export function deriveProductStructure(p,a,investmentOption='Balanced'){const capital=retirementCapital(p),couple=p.relationshipStatus==='couple',totalSuper=p.superBalance+(couple?p.partnerSuper:0),share=couple?(totalSuper?p.superBalance/totalSuper:.5):1;return {capital,investmentOption,accountBasedPension:capital*(a.I+a.F)/100,lifetimeIncomeAllocation:capital*a.E/100,liquidReserve:capital*a.L/100,lifeAllocation:a,payoutFactor:(p.lifetimePayout??5.5)/100,pensionFraction:clamp((grossRetirementCapital(p)-p.otherAssets)/Math.max(1,grossRetirementCapital(p)),0,1),memberShare:share,partnerRetirementAge:(p.partnerAge??p.age)+p.retirementAge-p.age};}
export function calculateLifetimeIncome(s){return s.lifetimeIncomeAllocation*s.payoutFactor;}
export function calculateAccessibleCapital(s){return s.accountBasedPension+s.liquidReserve;}
export function deemedIncome(financialAssets,couple){const t=couple?R.deemingCouple:R.deemingSingle;return Math.min(Math.max(0,financialAssets),t)*R.deemingLow+Math.max(0,financialAssets-t)*R.deemingHigh;}
export function lifetimeAssessableAssets(p,s,age=p.retirementAge){const years=Math.max(0,age-p.retirementAge),inflation=Math.pow(1.025,years);const owners=p.relationshipStatus==='couple'?[{start:p.retirementAge,share:s.memberShare},{start:s.partnerRetirementAge,share:1-s.memberShare}]:[{start:p.retirementAge,share:1}];return owners.reduce((sum,o)=>sum+s.lifetimeIncomeAllocation*o.share*(o.start+years>=R.lifetimeThresholdAge&&years>=R.lifetimeMinYears?R.lifetimeAssetLater:R.lifetimeAssetInitial)/inflation,0);}
export function pensionAssessment(p,s,age=p.retirementAge,balances={abp:s.accountBasedPension,cash:s.liquidReserve}){const couple=p.relationshipStatus==='couple',years=age-p.retirementAge,eligible=(age>=67?1:0)+(couple&&s.partnerRetirementAge+years>=67?1:0),financialAssets=Math.max(0,balances.abp)+Math.max(0,balances.cash),lifetimeAssets=lifetimeAssessableAssets(p,s,age),assessableAssets=financialAssets+lifetimeAssets+(p.nonFinancialAssets??0),deemed=deemedIncome(financialAssets,couple),assessableIncome=deemed+calculateLifetimeIncome(s)*.6+(p.otherIncome??0),max=(couple?R.maxFortnightCoupleEach*2:R.maxFortnightSingle)*26,assetsFree=couple?(p.homeowner?R.assetsCoupleHome:R.assetsCoupleRent):(p.homeowner?R.assetsSingleHome:R.assetsSingleRent),incomeFree=(couple?R.incomeFreeCoupleFortnight:R.incomeFreeSingleFortnight)*26,portion=couple?eligible/2:eligible;
// Continuous asset taper: omits the legislative $250 asset rounding and payment rounding.
const assetTest=clamp(max-Math.max(0,assessableAssets-assetsFree)*R.assetsTaperAnnualPerDollar,0,max)*portion,incomeTest=clamp(max-Math.max(0,assessableIncome-incomeFree)*.5,0,max)*portion,payment=p.pensionExpectation==='none'?0:Math.min(assetTest,incomeTest);return {payment,assetTest,incomeTest,assessableAssets,assessableIncome,deemedIncome:deemed,lifetimeAssets,eligibleCount:eligible,limitingTest:eligible===0?'Not yet age eligible':p.pensionExpectation==='none'?'Excluded by you':Math.abs(assetTest-incomeTest)<.01?'Both tests':assetTest<incomeTest?'Assets test':'Income test'};}
export function calculateAgePension(p,s,age=p.retirementAge,balances){return pensionAssessment(p,s,age,balances).payment;}
export function minimumPensionRate(age){return age<65?.04:age<75?.05:age<80?.06:age<85?.07:age<90?.09:age<95?.11:.14;}
export function project(p,s,prefs=defaultPreferences){let abp=s.accountBasedPension,cash=s.liquidReserve;const a=s.lifeAllocation,life=calculateLifetimeIncome(s),r={Growth:.03,Balanced:.02,Conservative:.01}[s.investmentOption],earlyDraw=s.capital*(a.I/100*.095+a.F/100*.015),laterDraw=s.capital*(a.I/100*.035+a.F/100*.027)*[.9,1,1.15][prefs.laterSpending],rows=[];let depletedAge=null,shortfallAge=null;
for(let age=p.retirementAge;age<=95;age++){const t=age-p.retirementAge,assessment=pensionAssessment(p,s,age,{abp,cash}),plannedOwn=t<10?earlyDraw:laterDraw,openingAbp=abp,openingCash=cash;abp*=1+r;const minRate=p.relationshipStatus==='couple'?minimumPensionRate(age)*s.memberShare+minimumPensionRate(s.partnerRetirementAge+t)*(1-s.memberShare):minimumPensionRate(age),minimumDraw=openingAbp*minRate*s.pensionFraction,withdrawal=Math.min(abp,Math.max(plannedOwn,minimumDraw)),spentFromAbp=Math.min(plannedOwn,withdrawal);abp-=withdrawal;cash+=withdrawal-spentFromAbp;const spentFromCash=Math.min(cash,Math.max(0,plannedOwn-spentFromAbp));cash-=spentFromCash;const actualOwn=spentFromAbp+spentFromCash;if(shortfallAge===null&&plannedOwn-actualOwn>1)shortfallAge=age;if(depletedAge===null&&abp+cash<1&&s.capital>0)depletedAge=age;rows.push({age,openingAbp,openingCash,closingAbp:abp,closingCash:cash,accessibleBalance:abp+cash,agePension:assessment.payment,lifetimeIncome:life,otherIncome:p.otherIncome??0,spending:actualOwn+life+assessment.payment+(p.otherIncome??0),plannedOwn,actualOwn,withdrawal,reinvested:withdrawal-spentFromAbp,assessment});}
const average=xs=>xs.length?xs.reduce((n,x)=>n+x.spending,0)/xs.length:0;return {rows,earlyIncome:average(rows.slice(0,10)),laterIncome:rows.length>10?average(rows.slice(10)):null,earlyYearsCount:Math.min(10,rows.length),laterYearsCount:Math.max(0,rows.length-10),earlyDraw,laterDraw,shortfallAge,depletedAge,futureBalance:rows.find(x=>x.age===90)?.openingAbp+rows.find(x=>x.age===90)?.openingCash||0};}
export function calculateEarlyRetirementIncome(p,s,prefs){return project(p,s,prefs).earlyIncome;}
export function calculateLaterRetirementIncome(p,s,prefs){return project(p,s,prefs).laterIncome;}
export function calculateProjectedFutureBalance(p,s,prefs){return project(p,s,prefs).futureBalance;}
export function calculate(p,prefs,c){const a=allocation(c,p),option=deriveInvestmentApproach(p,prefs,deriveInitialLifeAllocation(p,prefs)),s=deriveProductStructure(p,a,option),projection=project(p,s,prefs),assessment=pensionAssessment(p,s),at67=projection.rows.find(row=>row.age===Math.max(67,p.retirementAge)),lifetimeIncome=calculateLifetimeIncome(s);return {a,s,...projection,assessment,lifetimeIncome,agePension:assessment.payment,agePensionAt67:at67?.agePension??0,reliableIncome:lifetimeIncome+assessment.payment,accessibleCapital:calculateAccessibleCapital(s),reserve:s.liquidReserve};}
